name: Релиз проекта

on:
  workflow_dispatch:
    inputs:
      version:
        description: Версия релиза
        required: true
        type: string

jobs:
  changelog:
    uses: ExEr7um/workflows/.github/workflows/changelog.yml@v0.7.2
    with:
      version: ${{ inputs.version }}
