name: Публикация на npm

on:
  workflow_run:
    workflows: [Релиз проекта]
    types: [completed]

jobs:
  publish:
    uses: ExEr7um/workflows/.github/workflows/publish-npm.yml@v0.7.2
    with:
      build: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
