name: Публикация на npm

on:
  workflow_run:
    workflows: [Релиз проекта]
    types: [completed]

jobs:
  publish:
    uses: ExEr7um/workflows/.github/workflows/publish.yml@v0.6.2
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
