name: Публикация на npm

on:
  workflow_run:
    workflows: [Релиз проекта]
    types: [completed]

jobs:
  publish:
    uses: ExEr7um/workflows/.github/workflows/publish-npm.yml@v0.9.0
    with:
      build: true
